#nolint:(?!gosec)(?!dupl)(?!funlen)(?!staticcheck)(?!forbidigo)(?!cyclop)
linters-settings:
  funlen:
    lines: 100
    statements: 50
  cyclop:
    max-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gci:
    sections:
      - standard
      - default
      - prefix(gitlab.rtbrick.net)
  nolintlint:
    allow-unused: false
    allow-no-explanation: []
issues:
  exclude-rules:
    - linters:
        - funlen
        - cyclop
        - goerr113
        - dupl
        - forbidigo
        - gochecknoinits
        - gosec
        - staticcheck
        - goconst
        - goimports
      path: _test.go

  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'

linters:
  disable-all: true
  enable:
    - dupl
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    # - revive
    - staticcheck
    - unused
    - nolintlint
    - funlen
    - cyclop
    # - goerr113
    - forbidigo
    - gosec
    - staticcheck
    - goconst